universe                =vanilla
executable              = submit_3.sh
Should_Transfer_Files   = YES
WhenToTransferOutput    = ON_EXIT_OR_EVICT
+AcctGroup              = group_cmsuser.jkrupa
+AccountingGroup        = group_cmsuser.jkrupa
+HAS_GPU                = False
Transfer_Input_Files    = submit_3.sh, /uscms/home/jkrupa/nobackup/hcal_gnn/CMSSW_11_1_0_pre8.tgz
arguments               = $(ClusterId)$(ProcId) x test_instance_segmentation /home/jkrupa/x509up
output                  = logtest_instance_segmentation/xpu.$(ClusterId).$(ProcId).out
error                   = logtest_instance_segmentation/xpu.$(ClusterId).$(ProcId).err
log                     = logtest_instance_segmentation/xpu.$(ClusterId).$(ProcId).log
request_memory          = 4000
x509userproxy           = /uscms/home/jkrupa/x509up
queue 190
