universe                =vanilla
executable              = submit_3.sh
Should_Transfer_Files   = YES
WhenToTransferOutput    = ON_EXIT_OR_EVICT
+AcctGroup              = group_cmsuser.jkrupa
+AccountingGroup        = group_cmsuser.jkrupa
Transfer_Input_Files    = submit_3.sh, /home/jkrupa/pf_studies/CMSSW_10_5_0_pre2.tgz
arguments               = $(ClusterId)$(ProcId) 40 5 /home/jkrupa/x509up
output                  = output/40pu.$(ClusterId).$(ProcId).out
error                   = error/40pu.$(ClusterId).$(ProcId).err
log                     = log/40pu.$(ClusterId).$(ProcId).log
request_memory          = 4000
x509userproxy           = /home/jkrupa/x509up
+JobFlavour = "workday"  
queue 200
